# Generated by Django 5.2.6 on 2025-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0003_payment_gateway_reference_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedian',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comedians/'),
        ),
    ]
