# Generated by Django 5.2.6 on 2025-09-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0004_comedian_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('sponsor_name', models.CharField(default='NBC Kiganjani', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='has_used_free_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_free_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='quantity',
            field=models.IntegerField(choices=[(1, '1 Vote - FREE (Sponsored by NBC Kiganjani)'), (5, '5 Votes - TZS 1,000'), (10, '10 Votes - TZS 2,000'), (50, '50 Votes - TZS 5,000')]),
        ),
        migrations.AddField(
            model_name='vote',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_bot.ad'),
        ),
    ]
