# Generated by Django 5.2.4 on 2025-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0005_ad_user_has_used_free_vote_vote_is_free_vote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomineesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Comedian Bora wa Mwezi', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nominees/')),
                ('description', models.TextField(blank=True, help_text='Description text to show with the image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
