# Generated by Django 5.2.4 on 2025-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0006_nomineesimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBCLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TEMBELEA NBC', max_length=200)),
                ('url', models.URLField(help_text='Link to open when TEMBELEA NBC button is clicked')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
